import React from 'react';
import type { Meta, StoryObj } from '@storybook/react';
import { Spinner } from './Spinner';
const meta: Meta<typeof Spinner> = { title: 'Components/Feedback/Spinner', component: Spinner, tags: ['autodocs'], argTypes: { size: { control: 'select', options: ['sm', 'md', 'lg'] } } };
export default meta;
type Story = StoryObj<typeof Spinner>;
export const Default: Story = {};
export const Small: Story = { args: { size: 'sm' } };
export const Large: Story = { args: { size: 'lg' } };
export const CustomLabel: Story = { args: { label: 'Processing...' } };
export const AllSizes: Story = { render: () => (<div className="flex items-center gap-4"><Spinner size="sm" /><Spinner size="md" /><Spinner size="lg" /></div>) };
