/**
 * DS0 Token Build Pipeline
 *
 * Reads source tokens from tokens/ directory
 * Uses StyleDictionary to generate:
 *   - CSS custom properties   → packages/tokens/css/variables.css
 *   - Tailwind preset         → packages/tokens/tailwind/preset.js
 *   - React Native tokens     → packages/tokens/react-native/tokens.js
 *   - Resolved JSON           → packages/tokens/json/resolved.json
 */

import StyleDictionary from 'style-dictionary';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');

const tokenSources = [
    `${ROOT}/tokens/_core/*.json`,
    `${ROOT}/tokens/_semantic/*.json`,
    `${ROOT}/tokens/themes/default.json`,
];

// --- CSS Custom Properties ---

const cssConfig = {
    source: tokenSources,
    platforms: {
        css: {
            transformGroup: 'css',
            prefix: 'ds0',
            buildPath: `${ROOT}/packages/tokens/css/`,
            files: [
                {
                    destination: 'variables.css',
                    format: 'css/variables',
                    options: { outputReferences: true },
                },
            ],
        },
    },
};

// --- Tailwind Preset ---

StyleDictionary.registerFormat({
    name: 'tailwind/preset',
    format: function ({ dictionary }) {
        const colors = {};
        const spacing = {};
        const borderRadius = {};
        const fontSize = {};
        const fontFamily = {};
        const fontWeight = {};
        const lineHeight = {};
        const letterSpacing = {};
        const transitionDuration = {};
        const transitionTimingFunction = {};

        dictionary.allTokens.forEach((token) => {
            const cssVar = `var(--ds0-${token.path.join('-')})`;

            if (token.path[0] === 'color' && token.path.length === 2) {
                colors[token.path[1]] = cssVar;
            } else if (token.path[0] === 'color' && token.path.length === 3) {
                const key = `${token.path[1]}-${token.path[2]}`;
                colors[key] = cssVar;
            }
            if (token.path[0] === 'spacing') spacing[token.path[1]] = cssVar;
            if (token.path[0] === 'radius') borderRadius[token.path[1]] = cssVar;
            if (token.path[0] === 'fontSize') fontSize[token.path[1]] = cssVar;
            if (token.path[0] === 'fontFamily') fontFamily[token.path[1]] = cssVar;
            if (token.path[0] === 'fontWeight') fontWeight[token.path[1]] = cssVar;
            if (token.path[0] === 'lineHeight') lineHeight[token.path[1]] = cssVar;
            if (token.path[0] === 'letterSpacing') letterSpacing[token.path[1]] = cssVar;
            if (token.path[0] === 'duration') transitionDuration[token.path[1]] = cssVar;
            if (token.path[0] === 'easing') transitionTimingFunction[token.path[1]] = cssVar;
        });

        const preset = {
            theme: {
                extend: {
                    colors,
                    spacing,
                    borderRadius,
                    fontSize,
                    fontFamily,
                    fontWeight,
                    lineHeight,
                    letterSpacing,
                    transitionDuration,
                    transitionTimingFunction,
                },
            },
        };

        return [
            '// AUTO-GENERATED by DS0 token pipeline — do not edit manually',
            '// Source: tokens/**/*.json → StyleDictionary → this file',
            '',
            '/** @type {import("tailwindcss").Config} */',
            `export default ${JSON.stringify(preset, null, 2)};`,
            '',
        ].join('\n');
    },
});

const tailwindConfig = {
    source: tokenSources,
    platforms: {
        tailwind: {
            transformGroup: 'js',
            buildPath: `${ROOT}/packages/tokens/tailwind/`,
            files: [
                {
                    destination: 'preset.js',
                    format: 'tailwind/preset',
                },
            ],
        },
    },
};

// --- React Native ---

const rnConfig = {
    source: tokenSources,
    platforms: {
        'react-native': {
            transformGroup: 'react-native',
            buildPath: `${ROOT}/packages/tokens/react-native/`,
            files: [
                {
                    destination: 'tokens.js',
                    format: 'javascript/module-flat',
                },
            ],
        },
    },
};

// --- Resolved JSON ---

const jsonConfig = {
    source: tokenSources,
    platforms: {
        json: {
            transformGroup: 'js',
            buildPath: `${ROOT}/packages/tokens/json/`,
            files: [
                {
                    destination: 'resolved.json',
                    format: 'json/flat',
                },
            ],
        },
    },
};

// --- Build ---

async function build() {
    console.log('\n🎨 DS0 Token Pipeline\n');

    try {
        const configs = [
            { name: 'CSS custom properties', config: cssConfig },
            { name: 'Tailwind preset', config: tailwindConfig },
            { name: 'React Native tokens', config: rnConfig },
            { name: 'Resolved JSON', config: jsonConfig },
        ];

        for (const { name, config } of configs) {
            console.log(`📦 Building ${name}...`);
            const sd = new StyleDictionary(config);
            await sd.buildAllPlatforms();
        }

        console.log('\n✅ All tokens built successfully!\n');
    } catch (error) {
        console.error('\n❌ Token build failed:', error.message);
        process.exit(1);
    }
}

build();
