import { defineConfig } from 'tsup';

export default defineConfig({
    entry: [
        'src/index.ts',
        'src/accordion/index.ts',
        'src/alert/index.ts',
        'src/aspect-ratio/index.ts',
        'src/avatar/index.ts',
        'src/badge/index.ts',
        'src/breadcrumb/index.ts',
        'src/button/index.ts',
        'src/card/index.ts',
        'src/checkbox/index.ts',
        'src/code/index.ts',
        'src/container/index.ts',
        'src/dialog/index.ts',
        'src/divider/index.ts',
        'src/drawer/index.ts',
        'src/form/index.ts',
        'src/grid/index.ts',
        'src/heading/index.ts',
        'src/icon-button/index.ts',
        'src/label/index.ts',
        'src/link/index.ts',
        'src/pagination/index.ts',
        'src/popover/index.ts',
        'src/progress/index.ts',
        'src/radio-group/index.ts',
        'src/select/index.ts',
        'src/skeleton/index.ts',
        'src/slider/index.ts',
        'src/spinner/index.ts',
        'src/stack/index.ts',
        'src/switch/index.ts',
        'src/table/index.ts',
        'src/tabs/index.ts',
        'src/text/index.ts',
        'src/text-area/index.ts',
        'src/text-field/index.ts',
        'src/toast/index.ts',
        'src/toggle/index.ts',
        'src/toggle-group/index.ts',
        'src/tooltip/index.ts',
        'src/utils/cn.ts',
    ],
    format: ['esm'],
    dts: true,
    splitting: true,
    sourcemap: true,
    clean: true,
    treeshake: true,
    external: ['react', 'react-dom'],
});
